### ISSUE TITLE
All participants should update their database.

### ISSUE THREAD

**Issue by hayriyeanill** [hayriyeanill/CMS#3]

**Comment by damla** [comment]
USERS table created.
![image](https://user-images.githubusercontent.com/24878421/56679842-ab9d0000-66ce-11e9-9ac6-d6fb128f2e3e.png)
![image](https://user-images.githubusercontent.com/24878421/56679871-b6f02b80-66ce-11e9-955d-8013f10b3b2a.png)

**Comment by damla** [comment]
COURSES table created.
![image](https://user-images.githubusercontent.com/24878421/56680502-097e1780-66d0-11e9-9dca-9abf1ed3e532.png)
![image](https://user-images.githubusercontent.com/24878421/56680399-dc316980-66cf-11e9-8a00-29f972c2005b.png)

**Comment by hayriyeanill** [comment]
db updated

**Comment by hayriyeanill** [comment]
[assignments-resources.xlsx](https://github.com/hayriyeanill/CMS/files/3124071/assignments-resources.xlsx)
RESOURCES table created.
![image](https://user-images.githubusercontent.com/24878421/56893278-c71b5880-6a8a-11e9-8ce3-9458d95347fe.png)

![resources table](https://user-images.githubusercontent.com/37445083/56852218-fca43280-6920-11e9-87f8-2821d498e4a3.PNG)
ASSIGNMENTS table created
![assignments data type](https://user-images.githubusercontent.com/37445083/56852230-3412df00-6921-11e9-884d-39a87102b091.PNG)

**Comment by hayriyeanill** [comment]
ANSWERS table created
![answer data type](https://user-images.githubusercontent.com/37445083/56867801-77894e00-69f2-11e9-8cf3-c0be1a597141.PNG)

**Comment by damla** [comment]
CONTENT column in tables has to change as CONTENT_A for ASSIGNMENT table and CONTENT_R for RESOURCES table.

**Comment by damla** [comment]
STUDENTS table created.
![image](https://user-images.githubusercontent.com/24878421/56900817-68aca500-6a9f-11e9-8d86-7a3a2ea2a743.png)
[STUDENTS.xlsx](https://github.com/hayriyeanill/CMS/files/3127675/STUDENTS.xlsx)

**Comment by hayriyeanill** [comment]
GRADES table created
![GRADES](https://user-images.githubusercontent.com/37445083/56922502-010f4d80-6ad1-11e9-9960-feee1b553975.PNG)
[GRADES.xlsx](https://github.com/hayriyeanill/CMS/files/3128957/GRADES.xlsx)

**Comment by damla** [comment]
Query to add grades;
[GRADES.txt](https://github.com/hayriyeanill/CMS/files/3131000/GRADES.txt)
